#!/usr/bin/env node
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..", "..");
const OUT_DIR = join(REPO_ROOT, "out");
const SRC_DIR = join(__dirname, "..", "src");
const DEST_JSON = join(SRC_DIR, "abis.json");
const DEST_JSONL = join(SRC_DIR, "abis.jsonl");
const DEST_TS = join(SRC_DIR, "generatedAbis.ts");

if (!existsSync(SRC_DIR)) {
  mkdirSync(SRC_DIR, { recursive: true });
}

function walk(dir) {
  if (!existsSync(dir)) return [];
  const entries = readdirSync(dir);
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) files.push(...walk(full));
    else if (entry.endsWith(".json")) files.push(full);
  }
  return files;
}

function isFromSrcDir(artifact) {
  const target = artifact?.metadata?.settings?.compilationTarget;
  if (!target) return false;
  return Object.keys(target).some((p) => p.startsWith("src/"));
}

function main() {
  const files = walk(OUT_DIR);
  let rawBytes = 0;
  let skipped = 0;

  const byQualifiedName = new Map();
  const nameToQualified = new Map();

  for (const file of files) {
    let artifact;
    try {
      artifact = JSON.parse(readFileSync(file, "utf8"));
    } catch {
      continue;
    }
    if (!Array.isArray(artifact.abi) || artifact.abi.length === 0) continue;
    if (!isFromSrcDir(artifact)) {
      skipped++;
      continue;
    }

    const sourcePath = Object.keys(artifact.metadata.settings.compilationTarget)[0];
    const contractName = artifact.metadata.settings.compilationTarget[sourcePath];
    const qualified = `${sourcePath}:${contractName}`;
    if (byQualifiedName.has(qualified)) continue;

    rawBytes += statSync(file).size;
    byQualifiedName.set(qualified, { sourcePath, name: contractName, abi: artifact.abi });

    if (!nameToQualified.has(contractName)) nameToQualified.set(contractName, new Set());
    nameToQualified.get(contractName).add(qualified);
  }

  const manifest = {};
  const jsonlLines = [];
  const sourcePathCounts = new Map();
  for (const { sourcePath } of byQualifiedName.values()) {
    sourcePathCounts.set(sourcePath, (sourcePathCounts.get(sourcePath) ?? 0) + 1);
  }

  for (const [qualified, { sourcePath, name, abi }] of byQualifiedName) {
    manifest[qualified] = abi;
    jsonlLines.push(JSON.stringify({ name, source: sourcePath, abi }));

    if (sourcePathCounts.get(sourcePath) === 1) {
      manifest[sourcePath] = qualified;
    }
    if (nameToQualified.get(name).size === 1) {
      manifest[name] = qualified;
    }
  }

  const jsonOut = JSON.stringify(manifest, null, 2);
  const jsonlOut = jsonlLines.join("\n") + "\n";

  writeFileSync(DEST_JSON, jsonOut);
  writeFileSync(DEST_JSONL, jsonlOut);

  // Generate strongly-typed TypeScript file with `as const` viem ABIs
  const tsExports = [];
  tsExports.push(`// Autogenerated by buildAbis.mjs — do not edit directly\n\n`);
  for (const [qualified, { name, abi }] of byQualifiedName) {
    const cleanIdentifier = qualified
      .replace(/^src\//, "")
      .replace(/\.sol:/, "_")
      .replace(/[^a-zA-Z0-9_]/g, "_");
    tsExports.push(`export const ${cleanIdentifier}Abi = ${JSON.stringify(abi)} as const;\n`);
    if (nameToQualified.get(name).size === 1) {
      tsExports.push(`export const ${name}Abi = ${cleanIdentifier}Abi;\n\n`);
    }
  }
  writeFileSync(DEST_TS, tsExports.join(""));

  console.log(`✓ Scanned ${files.length} artifact files under out/`);
  console.log(`✓ Included ${byQualifiedName.size} unique contracts from src/ (skipped ${skipped} non-src artifacts)`);
  console.log(`✓ Generated: ${DEST_JSON} (${(jsonOut.length / 1024).toFixed(1)} KB)`);
  console.log(`✓ Generated: ${DEST_TS} (${(statSync(DEST_TS).size / 1024).toFixed(1)} KB)`);
}

main();
